Q29. Write the Python class to find the validity of the string of the parentheses, '(', ')', '{', '}', '[' and '] and the brackets must be closed in the correct order, example - "()" and "()[]{}" are valid but "[)", "({[)]" and "{{{" are invalid.

In [18]:
class py_soln:
    def str_validity(self,str1):
        stack, pchar = [], {"(": ")", "{": "}", "[": "]"}
        for parenthese in str1:
            if parenthese in pchar:
                stack.append(parenthese)
            elif len(stack) == 0 or pchar[stack.pop()] != parenthese:
                return False
        return len(stack) == 0
       
    print(py_soln().str_validity("(){}[]"))
    print(py_soln().str_validity("()[{)}"))
    print(py_soln().str_validity("()"))

True
False
True


Q30. Write the Python class to get all possible unique subsets from a set of distinct integers?

In [19]:
class py_solution:
    def sub_sets(self, sset):
        return self.subsetsRecur([], sorted(sset))
    def subsetsRecur(self, current, sset):
        if sset:
            return self.subsetsRecur(current, sset[1:]) + self.subsetsRecur(current + [sset[0]], sset[1:])
        return [current]
print(py_solution().sub_sets([4,5,6]))

[[], [6], [5], [5, 6], [4], [4, 6], [4, 5], [4, 5, 6]]


Q31. Write the Python class to find a pair of elements (indices of the two numbers) from a given array whose sum equals the specific target number?

In [29]:
class py_solution:
    def twoSum(self, nums, target):
        lookup = {}
        for i, num in enumerate(nums):
            if target - num in lookup:
                return (lookup[target - num], i )
            lookup[num] = i
print("index1=%d, index2=%d" % py_solution().twoSum((10,20,10,40,50,60,70),50))   
            

index1=2, index2=3


Q32. Write the Python class to find the three elements that sum to zero from the set of n real numbers?

In [5]:
class py_sol:
    def three_sum(self,nums):
        nums, result, i = sorted(nums), [], 0
        while i < len(nums) - 2:
            j, k = i + 1, len(nums) - 1
            while j < k:
                if nums[i] + nums[j] + nums[k] < 0:
                    j += 1
                elif nums[i] + nums[j] + nums[k] > 0:
                    k -= 1
                else:
                    result.append([nums[i], nums[j], nums[k]])
                    j, k = j + 1, k - 1
                    while j < k and nums[j] == nums[j - 1]:
                        j += 1
                    while j < k and nums[k] == nums[k + 1]:
                        k -= 1
            i += 1
            while i < len(nums) - 2 and nums[i] == nums[i - 1]:
                i += 1
        return result
print(py_sol().three_sum([-25, -10, -7, -3, 2, 4, 8, 10]))         

[[-10, 2, 8], [-7, -3, 10]]


Q33. Write the Python class to implement pow(x, n)?

In [12]:
class py_solution:
    def pow(self,x,n):
        if x==0 or x==1 or n==1:
            return x
        if x==-1:
            if n%2 ==0:
                return 1
            else:
                return -1
        if n==0:
            return 1
        if n<0:
            return 1/self.pow(x,-n)
        val = self.pow(x,n//2)
        if n%2 ==0:
            return val*val
        return val*val*x
print(py_solution().pow(2, -3));
print(py_solution().pow(3, 5));
print(py_solution().pow(100, 0));
       
            


0.125
243
1


Q 34 Write the Python class which has two methods get_String and print_String. get_String accept the string from the user and

print_String print the string in upper case.

In [14]:
class IOString():
    def __init__(self):
        self.str1 = ""
    def get_String(self):
        self.str1 = input()
    def print_String(self):
        print(self.str1.upper())
str1 = IOString()
str1.get_String()
str1.print_String()

nisi
NISI


Q35. Write the Python class named Rectangle constructed by a length and width and the method which will compute the area of the rectangle?

In [16]:
class Rectangle:
    def __init__(self,l,w):
        self.length=l
        self.width=w
    def rect_area(self):
        area=self.length*self.width
        return area
rec=Rectangle(12,21)
print(rec.rect_area())

252


Q36. Write the Python class named Circle constructed by the radius and two methods which will compute the area and perimeter of the circle?

In [20]:
class circle:
    def __init__(self,r):
        self.radius=r
    def circle_Area(self):
        circle_area=3.141*self.radius**2
        return circle_area
    def circle_perimeter(self):
        circle_perimete=2*3.141*self.radius
        return circle_perimete
ca=circle(12)
print(ca.circle_Area())
print(ca.circle_perimeter())
        
        

452.304
75.384


Q37. Write the Python program to get the class name of an instance in Python?

In [21]:
import itertools
x = itertools.cycle('ABCD')
print(type(x).__name__)


cycle


Q38. Write the Python program to count the number of students of individual class?

In [23]:
from collections import Counter
classes = ( ('V', 1), ('VI', 1), ('V', 2), ('VI', 2), ('VI', 3), ('VII', 1),)
students = Counter(class_name for class_name, no_students in classes)
print(students)

Counter({'VI': 3, 'V': 2, 'VII': 1})


Q39. Write the Python program to create an instance of an OrderedDict using the given dictionary and sort dictionary during the creation and print members of the dictionary in reverse order?

In [24]:
from collections import OrderedDict
dict = {'Afghanistan': 93, 'Albania': 355, 'Algeria': 213, 'Andorra': 376, 'Angola': 244}
new_dict = OrderedDict(dict.items())
for key in new_dict:
    print (key, new_dict[key])
print("\nIn reverse order:")
for key in reversed(new_dict):
    print (key, new_dict[key])

Afghanistan 93
Albania 355
Algeria 213
Andorra 376
Angola 244

In reverse order:
Angola 244
Andorra 376
Algeria 213
Albania 355
Afghanistan 93


Q40. Write the Python program to compare two unordered lists (not sets)?
Expected Output: False

In [26]:
from collections import Counter
def compare_lists(x, y):
    return Counter(x) == Counter(y)
n1 = [20, 10, 30, 10, 20, 30]
n2 = [30, 20, 10, 30, 20, 50] 
print(compare_lists(n1, n2))

False


Q41. Write the Python program to get an array buffer information?

In [27]:
from array import array
a = array("I", (12,25))
print("Array buffer start address in memory and number of elements.")
print(a.buffer_info())

Array buffer start address in memory and number of elements.
(2176502200208, 2)


Q42. Write the Python program to convert an array to an array of machine values and return the bytes representation?

In [29]:
import array
import binascii
a = array.array('i', [1,2,3,4,5,6])
print("Original array:")
print('A1:', a)
bytes_array = a.tobytes()
print('Array of bytes:', binascii.hexlify(bytes_array))

Original array:
A1: array('i', [1, 2, 3, 4, 5, 6])
Array of bytes: b'010000000200000003000000040000000500000006000000'



Q43. Write the Python program to read a string and interpreting the string as an array of machine values?

In [31]:
from array import array
import binascii
array1 = array('i', [7, 8, 9, 10])
print('array1:', array1)
as_bytes = array1.tobytes() 
print('Bytes:', binascii.hexlify(as_bytes))
array2 = array('i')
array2.frombytes(as_bytes)
print('array2:', array2)

array1: array('i', [7, 8, 9, 10])
Bytes: b'0700000008000000090000000a000000'
array2: array('i', [7, 8, 9, 10])


Q44. Write the Python program to push three items into the heap and return the smallest item from the heap. Also, return and pop the smallest item from the heap?

In [32]:
import heapq
heap = []
heapq.heappush(heap, ('V', 3))
heapq.heappush(heap, ('V', 2)) 
heapq.heappush(heap, ('V', 1))
print("Items in the heap:")
for a in heap:
    print(a)
print("----------------------")
print("The smallest item in the heap:")
print(heap[0])
print("----------------------")
print("Pop the smallest item in the heap:")
heapq.heappop(heap)
for a in heap:
    print(a)

Items in the heap:
('V', 1)
('V', 3)
('V', 2)
----------------------
The smallest item in the heap:
('V', 1)
----------------------
Pop the smallest item in the heap:
('V', 2)
('V', 3)


Q45. Write the Python program to locate the left insertion point for a specified value in sorted order?

In [33]:
import bisect
def index(a, x):
    i = bisect.bisect_left(a, x)
    return i
a = [1,2,4,5]
print(index(a, 6))
print(index(a, 3))

4
2


Q46. Write the Python program to create the FIFO queue?

In [34]:
import queue
q = queue.Queue()
#insert items at the end of the queue
for x in range(4):
    q.put(str(x))
#remove items from the head of the queue
while not q.empty():
    print(q.get(), end=" ")
    print("\n")

0 

1 

2 

3 



Q47. Write the Python program to calculate the harmonic sum of n-1.

In [35]:
def harmonic_sum(n):
    if n < 2:
        return 1
    else:
        return 1 / n + (harmonic_sum(n - 1))
print(harmonic_sum(7))
print(harmonic_sum(4))

2.5928571428571425
2.083333333333333


Q48. Write the NumPy program to create a 2d array with 6 on the border and 0 inside?

In [38]:
import numpy as np
x = np.ones((5,5))
print("Original array:")
print(x)
print("1 on the border and 0 inside in the array")
x[1:-1,1:-1] = 0
print(x)

Original array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Q49. Write the NumPy program to create a 8x8 matrix and fill it with the checkerboard pattern?

In [40]:
import numpy as np
x = np.ones((3,3))
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Q50. Write the NumPy program to create an empty and a full array.

In [42]:
import numpy as np
# Create an empty array
x = np.empty((3,4))
print(x)
# Create a full array
y = np.full((3,3),6)
print(y)

[[1.07529947e-311 2.42092166e-322 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 2.92966904e-033 7.11818555e-091 2.87922113e+180]
 [2.83104471e-033 1.16130307e-046 6.99196248e+228 8.00842647e+165]]
[[6 6 6]
 [6 6 6]
 [6 6 6]]
