Q51. Write the NumPy program to convert the values of Centigrade degrees into the Fahrenheit degrees and the centigrade values are stored in the NumPy array.

In [1]:
import numpy as np
fvalues = [0, 12, 45.21, 34, 99.91]
F = np.array(fvalues)
print("Values in Fahrenheit degrees:")
print(F)
print("Values in Centigrade degrees:") 
print(5*F/9 - 5*32/9)

Values in Fahrenheit degrees:
[ 0.   12.   45.21 34.   99.91]
Values in Centigrade degrees:
[-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]



Q52. Write the NumPy program to find the real and imaginary parts of an array of complex numbers?
    

In [9]:
import numpy as np
x = np.sqrt([1+0j])
y = np.sqrt([0+1j])
print("Original array:x ",x)
print("Original array:y ",y)
print("Real part of the array:")
print(x.real)
print(y.real)
print("Imaginary part of the array:")
print(x.imag)
print(y.imag)



Original array:x  [1.+0.j]
Original array:y  [0.70710678+0.70710678j]
Real part of the array:
[1.]
[0.70710678]
Imaginary part of the array:
[0.]
[0.70710678]


Q53. Write the NumPy program to test whether each element of a 1-D array is also present in the second array?

In [11]:
import numpy as np
a1=[ 0,10,20,40,60]
a2=[0,40]
s1=np.array(a1)
s2=np.array(a2)
print(np.in1d(s1,s2))


[ True False False  True False]


Q54. Write the NumPy program to find common values between two arrays?

In [15]:
import numpy as np
a1=[ 0,10,20,40,60]
a2=[0,40]
s1=np.array(a1)
s2=np.array(a2)
print("common values between two arrays- :",np.intersect1d(s1,s2))

common values between two arrays- : [ 0 40]


Q55. Write the NumPy program to get the unique elements of an array?

In [20]:
import numpy as np
a1=np.array([10,10,20,20,30,30])
print("Unique values :-",np.unique(a1))


Unique values :- [10 20 30]


Q56. Write the NumPy program to find the set exclusive-or of two arrays. Set exclusive-or will return the sorted, unique values that are in only one (not both) of the input arrays?

In [23]:
import numpy as np
Array1=[ 0, 10, 20, 40, 60 ,80]
Array2=[10, 30, 40, 50, 70]
a1=np.array(Array1)
a2=np.array(Array2)
print("Array1: ",a1)
print("Array2: ",a2)
print("Unique values that are in only one (not both) of the input arrays:")
print(np.setxor1d(a1, a2))

Array1:  [ 0 10 20 40 60 80]
Array2:  [10 30 40 50 70]
Unique values that are in only one (not both) of the input arrays:
[ 0 20 30 50 60 70 80]


Q57. Write the NumPy program to test if all elements in an array evaluate to True ?

In [25]:
import numpy as np
print(np.all([[True,False],[True,True]]))
print(np.all([[True,True],[True,True]]))
print(np.all([10, 20, 0, -50]))
print(np.all([10, 20, -50]))

False
True
False
True


Q58 Write the NumPy program to test whether any array element along the given axis evaluates to True?

In [27]:
import numpy as np
print(np.any([[False,False],[False,False]]))
print(np.any([[True,True],[True,True]]))
print(np.any([10, 20, 0, -50]))
print(np.any([10, 20, -50]))

False
True
True
True


Q59. Write the NumPy program to construct an array by repeating?

In [31]:
a = [1, 2, 3, 4]
print("Original array")
print(a)
print("Repeating 2 times")
x = np.tile(a, 2)
print(x)
print("Repeating 3 times")
x = np.tile(a, 3)
print(x)


Original array
[1, 2, 3, 4]
Repeating 2 times
[1 2 3 4 1 2 3 4]
Repeating 3 times
[1 2 3 4 1 2 3 4 1 2 3 4]


Q60. Write the NumPy program to find the indices of the maximum and minimum values with the given axis of an array?

In [32]:
import numpy as np
x = np.array([1, 2, 3, 4, 5, 6])
print("Original array: ",x)
print("Maximum Values: ",np.argmax(x))
print("Minimum Values: ",np.argmin(x))

Original array:  [1 2 3 4 5 6]
Maximum Values:  5
Minimum Values:  0
